
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Tue Jul 04 19:26:17 UYT 2017
//----------------------------------------------------

package java_quaero.parser;

/** CUP generated interface containing symbol constants. */
public interface ParserSym {
  /* terminals */
  public static final int BICOND = 10;
  public static final int TRUE = 6;
  public static final int CONJ = 7;
  public static final int DISY = 8;
  public static final int EOF = 0;
  public static final int PARI = 3;
  public static final int COND = 9;
  public static final int FALSE = 5;
  public static final int ID = 13;
  public static final int IGUAL = 12;
  public static final int error = 1;
  public static final int PUNTOCOMA = 11;
  public static final int PARD = 4;
  public static final int NEG = 2;
}

