
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Sat Jul 08 14:53:31 UYT 2017
//----------------------------------------------------

package java_quaero.parser;

/** CUP generated interface containing symbol constants. */
public interface Tokens {
  /* terminals */
  public static final int NUM = 4;
  public static final int ID = 2;
  public static final int STRING = 3;
  public static final int error = 1;
  public static final int BOOL = 5;
  public static final int EOF = 0;
}

